import { jsPDF } from 'jspdf';
import * as fabric from 'fabric';

interface ProjectMetadata {
  projectName: string;
  engineerName: string;
  organisationName: string;
  date: string;
  region: string;
  projectId: string;
}

/**
 * Generates a professional engineering PDF plot from the Fabric.js canvas.
 * Optimized for A4 Landscape printing.
 */
export const generatePdfPlot = (
  canvas: fabric.Canvas,
  metadata: ProjectMetadata
) => {
  // 1. Initialize A4 Landscape (297 x 210 mm)
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // 2. Capture Canvas at high-res (2x multiplier)
  const canvasDataUrl = canvas.toDataURL({
    format: 'png',
    quality: 1,
    multiplier: 2,
    enableRetinaScaling: true,
  });

  // 3. Document Framing (Professional Blue Border)
  doc.setDrawColor(15, 23, 42); // slate-900
  doc.setLineWidth(0.5);
  doc.rect(5, 5, pageWidth - 10, pageHeight - 10);

  // 4. Place Canvas Image (Fit to frame, maintaining aspect ratio)
  // We leave space for the title block at the bottom (approx 40mm)
  const drawWidth = pageWidth - 20;
  const drawHeight = pageHeight - 60;
  doc.addImage(canvasDataUrl, 'PNG', 10, 10, drawWidth, drawHeight);

  // 5. Title Block (Bottom-Right Logic)
  const tbX = pageWidth - 120;
  const tbY = pageHeight - 45;
  const tbWidth = 115;
  const tbHeight = 40;

  // Background for Title Block
  doc.setFillColor(248, 250, 252); // slate-50
  doc.rect(tbX, tbY, tbWidth, tbHeight, 'F');
  doc.setDrawColor(15, 23, 42);
  doc.rect(tbX, tbY, tbWidth, tbHeight);

  // Internal Grid for Title Block
  doc.line(tbX + 50, tbY, tbX + 50, tbY + tbHeight); // Vertical divider
  doc.line(tbX, tbY + 15, tbX + tbWidth, tbY + 15); // Horizontal divider

  // Header - Firm Name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('ENGINEERING FIRM / ORG', tbX + 2, tbY + 5);
  doc.setFontSize(14);
  doc.setTextColor(16, 185, 129); // emerald-500
  doc.text(metadata.organisationName.toUpperCase(), tbX + 2, tbY + 12);

  // Project Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(8);
  doc.text('PROJECT NAME', tbX + 52, tbY + 5);
  doc.setFontSize(10);
  doc.text(metadata.projectName || 'UNNAMED_SCHEMA', tbX + 52, tbY + 10);

  // Metadata Grid
  doc.setFontSize(7);
  doc.text('ENGINEER OF RECORD', tbX + 2, tbY + 20);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(metadata.engineerName, tbX + 2, tbY + 25);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.text('DATE', tbX + 52, tbY + 20);
  doc.setFont('helvetica', 'normal');
  doc.text(metadata.date, tbX + 52, tbY + 25);

  doc.setFont('helvetica', 'bold');
  doc.text('REGION', tbX + 80, tbY + 20);
  doc.setFont('helvetica', 'normal');
  doc.text(metadata.region, tbX + 80, tbY + 25);

  doc.setFont('helvetica', 'bold');
  doc.text('PROJECT ID', tbX + 2, tbY + 32);
  doc.setFont('helvetica', 'normal');
  doc.text(metadata.projectId, tbX + 2, tbY + 37);

  doc.setFont('helvetica', 'bold');
  doc.text('SHEET NO.', tbX + 95, tbY + 32);
  doc.setFontSize(12);
  doc.text('M-101', tbX + 95, tbY + 38);

  // Watermark / Branding
  doc.setFontSize(6);
  doc.setTextColor(150, 150, 150);
  doc.text('GENERATED BY HVAC DESIGNPRO — CLOUD ENGINEERING ENGINE', 10, pageHeight - 7);

  // 6. Save or Stream
  doc.save(`HVAC_PLOT_${metadata.projectId}_${metadata.date.replace(/\//g, '-')}.pdf`);
};
